server:
  port: ${PORT:9090}
  address: 0.0.0.0

spring:
  sql.init.mode: never
  # DB 접속 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: info
    # Hibernate 설정은 공통에 선언되어 유지됨 (SQL: debug, bind: trace)

discodeit:
  storage:
    type: local
    local:
      root-path: ${user.dir}/data/discodeit/storage
