server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  # H2 Console 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
  # JPA 설정
  jpa:
    hibernate:
      # 테이블 자동 생성/삭제
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후 data.sql 실행하도록 설정
    defer-datasource-initialization: true

logging:
  level:
    root: debug

    # Hibernate 설정은 공통에 선언되어 유지됨 (SQL: debug, bind: trace)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
      show-components: always
    loggers:
      access: unrestricted


