server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      # 테이블 자동 생성/삭제
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

discodeit:
  storage:
    type: local

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.springframework.security: debug
    org.springframework.web: debug
    # Hibernate 설정은 공통에 선언되어 유지됨 (SQL: debug, bind: trace)

management:
  endpoint:
    health:
      show-details: always
      show-components: always
    loggers:
      access: unrestricted
  info:
    env:
      enabled: true

