server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  sql.init.mode: always
  # DB 접속 정보
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: debug
    # Hibernate 설정은 공통에 선언되어 유지됨 (SQL: debug, bind: trace)
